services:
  - type: worker
    name: force-sub-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your-token-here
      - key: API_ID
        value: your-api-id
      - key: API_HASH
        value: your-api-hash
      - key: CHANNEL
        value: @yourchannel
